---
- name: setup weather station
  hosts: weatherstation
  roles:
   - pip_dependencies
   - source_code

  tasks:
    - name: enable i2c
      shell: raspi-config nonint do_i2c 0
      become: true

    - name: install pip
      apt:
        name: python3-pip
        state: present
      become: true

